'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'
import DashboardHeader from '@/components/layout/DashboardHeader'
import { FolderOpen, FileText, Upload, Download, Trash2, Edit2, ChevronRight, Home, Plus, Save, X } from 'lucide-react'

type FileItem = {
  name: string
  type: 'dir' | 'file'
  size: string
  modified: string
  extension?: string
}

const rootFiles: FileItem[] = [
  { name: 'world', type: 'dir', size: '—', modified: '2024-06-12' },
  { name: 'world_nether', type: 'dir', size: '—', modified: '2024-06-10' },
  { name: 'world_the_end', type: 'dir', size: '—', modified: '2024-06-08' },
  { name: 'plugins', type: 'dir', size: '—', modified: '2024-06-11' },
  { name: 'logs', type: 'dir', size: '—', modified: '2024-06-12' },
  { name: 'cache', type: 'dir', size: '—', modified: '2024-06-09' },
  { name: 'server.properties', type: 'file', size: '2.1 KB', modified: '2024-06-10', extension: 'properties' },
  { name: 'paper.jar', type: 'file', size: '38.2 MB', modified: '2024-06-08', extension: 'jar' },
  { name: 'eula.txt', type: 'file', size: '0.2 KB', modified: '2024-06-08', extension: 'txt' },
  { name: 'ops.json', type: 'file', size: '0.5 KB', modified: '2024-06-09', extension: 'json' },
  { name: 'banned-players.json', type: 'file', size: '0.1 KB', modified: '2024-06-10', extension: 'json' },
  { name: 'whitelist.json', type: 'file', size: '0.3 KB', modified: '2024-06-11', extension: 'json' },
]

const serverProperties = `# Minecraft server properties
# Generated by Cubiq Host

motd=\u00A7aSurvivalSMP \u00A77| Cubiq Host
server-port=25565
max-players=20
difficulty=normal
gamemode=survival
online-mode=true
pvp=true
enable-command-block=true
spawn-protection=16
view-distance=10
simulation-distance=10
max-tick-time=60000
`

const fileIcons: Record<string, string> = {
  dir: '📁',
  jar: '☕',
  properties: '⚙️',
  json: '📋',
  txt: '📄',
  log: '📝',
  yml: '🔧',
  yaml: '🔧',
}

export default function FileManagerPage() {
  const [path, setPath] = useState<string[]>([])
  const [files] = useState<FileItem[]>(rootFiles)
  const [selectedFile, setSelectedFile] = useState<FileItem | null>(null)
  const [editContent, setEditContent] = useState('')
  const [editing, setEditing] = useState(false)
  const [saved, setSaved] = useState(false)

  const openFile = (file: FileItem) => {
    if (file.type === 'dir') {
      setPath(p => [...p, file.name])
    } else {
      setSelectedFile(file)
      if (file.name === 'server.properties') {
        setEditContent(serverProperties)
      } else {
        setEditContent(`# ${file.name}\n# File content would be loaded from Pterodactyl API`)
      }
    }
  }

  const handleSave = () => {
    setSaved(true)
    setEditing(false)
    setTimeout(() => setSaved(false), 2000)
  }

  const breadcrumb = ['root', ...path]

  return (
    <div className="flex flex-col flex-1 overflow-y-auto">
      <DashboardHeader title="File Manager" />
      <div className="p-6 flex flex-col gap-4">

        {/* Toolbar */}
        <div className="flex items-center justify-between gap-3 flex-wrap">
          {/* Breadcrumb */}
          <div className="flex items-center gap-1 text-xs font-mono">
            {breadcrumb.map((crumb, i) => (
              <div key={i} className="flex items-center gap-1">
                {i > 0 && <ChevronRight size={12} className="text-gray-600" />}
                <button
                  onClick={() => setPath(breadcrumb.slice(1, i + 1))}
                  className={`hover:text-mc-diamond transition-colors ${i === breadcrumb.length - 1 ? 'text-white' : 'text-gray-500'}`}
                >
                  {i === 0 ? <Home size={12} /> : crumb}
                </button>
              </div>
            ))}
          </div>

          <div className="flex gap-2">
            <button className="flex items-center gap-1 px-3 py-2 border border-mc-grass/40 text-mc-grass hover:bg-mc-grass/10 text-xs font-body uppercase transition-all">
              <Upload size={12} /> Upload
            </button>
            <button className="flex items-center gap-1 px-3 py-2 border border-mc-card-border text-gray-400 hover:text-white text-xs font-body uppercase transition-all">
              <Plus size={12} /> New File
            </button>
            <button className="flex items-center gap-1 px-3 py-2 border border-mc-card-border text-gray-400 hover:text-white text-xs font-body uppercase transition-all">
              <FolderOpen size={12} /> New Folder
            </button>
          </div>
        </div>

        <div className="flex gap-4 flex-col lg:flex-row">
          {/* File list */}
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex-1 mc-card border border-mc-card-border overflow-hidden">
            <div className="px-4 py-2 border-b border-mc-card-border bg-mc-dark-bg flex text-xs font-mono text-gray-500 uppercase">
              <span className="flex-1">Name</span>
              <span className="w-24 text-right">Size</span>
              <span className="w-28 text-right">Modified</span>
              <span className="w-20 text-right">Actions</span>
            </div>
            <div className="divide-y divide-mc-card-border max-h-96 overflow-y-auto">
              {path.length > 0 && (
                <div
                  onClick={() => setPath(p => p.slice(0, -1))}
                  className="flex items-center gap-3 px-4 py-3 hover:bg-mc-hover-bg cursor-pointer transition-colors"
                >
                  <span className="text-lg">📁</span>
                  <span className="text-gray-400 text-sm font-mono">..</span>
                </div>
              )}
              {files.map((file) => (
                <div
                  key={file.name}
                  onDoubleClick={() => openFile(file)}
                  onClick={() => setSelectedFile(file.type === 'file' ? file : null)}
                  className={`flex items-center gap-3 px-4 py-3 hover:bg-mc-hover-bg cursor-pointer transition-colors group ${
                    selectedFile?.name === file.name ? 'bg-mc-hover-bg border-l-2 border-l-mc-diamond' : ''
                  }`}
                >
                  <span className="text-lg flex-shrink-0">
                    {file.type === 'dir' ? fileIcons.dir : fileIcons[file.extension || ''] || '📄'}
                  </span>
                  <span className="flex-1 text-sm font-mono text-gray-300 group-hover:text-white transition-colors truncate">
                    {file.name}
                  </span>
                  <span className="w-24 text-right text-xs font-mono text-gray-600">{file.size}</span>
                  <span className="w-28 text-right text-xs font-mono text-gray-600">{file.modified}</span>
                  <div className="w-20 flex justify-end gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                    {file.type === 'file' && (
                      <>
                        <button onClick={e => { e.stopPropagation(); openFile(file); setEditing(true) }} className="p-1 text-gray-500 hover:text-mc-diamond transition-colors">
                          <Edit2 size={12} />
                        </button>
                        <button onClick={e => e.stopPropagation()} className="p-1 text-gray-500 hover:text-mc-diamond transition-colors">
                          <Download size={12} />
                        </button>
                      </>
                    )}
                    <button onClick={e => e.stopPropagation()} className="p-1 text-gray-500 hover:text-mc-redstone transition-colors">
                      <Trash2 size={12} />
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </motion.div>

          {/* File editor */}
          {selectedFile && selectedFile.type === 'file' && (
            <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} className="lg:w-96 mc-card border border-mc-card-border flex flex-col">
              <div className="px-4 py-3 border-b border-mc-card-border flex items-center justify-between">
                <span className="text-sm font-mono text-white">{selectedFile.name}</span>
                <div className="flex gap-2">
                  {editing ? (
                    <>
                      <button onClick={handleSave} className="flex items-center gap-1 px-2 py-1 text-xs bg-mc-grass border border-mc-grass-dark text-white">
                        <Save size={10} /> Save
                      </button>
                      <button onClick={() => setEditing(false)} className="p-1 text-gray-500 hover:text-white transition-colors">
                        <X size={14} />
                      </button>
                    </>
                  ) : (
                    <button onClick={() => setEditing(true)} className="flex items-center gap-1 px-2 py-1 text-xs border border-mc-card-border text-gray-400 hover:text-white transition-all">
                      <Edit2 size={10} /> Edit
                    </button>
                  )}
                </div>
              </div>
              <textarea
                value={editContent}
                onChange={e => setEditContent(e.target.value)}
                readOnly={!editing}
                className="flex-1 bg-transparent p-4 font-mono text-xs text-gray-300 focus:outline-none resize-none min-h-80"
                style={{ background: editing ? 'rgba(78,235,208,0.02)' : 'transparent' }}
              />
              {saved && (
                <div className="px-4 py-2 bg-mc-emerald/10 border-t border-mc-emerald/20 text-mc-emerald text-xs font-mono flex items-center gap-1">
                  <Save size={10} /> File saved successfully
                </div>
              )}
            </motion.div>
          )}
        </div>

        <p className="text-gray-600 text-xs font-mono">
          💡 Double-click to open files or navigate into folders. Use SFTP for bulk uploads.
        </p>
      </div>
    </div>
  )
}
